onnx_segmentation_detector:
  ros__parameters:
    conf_threshold: 0.3
    mask_threshold: 0.3
    providers:
      #- TensorrtExecutionProvider
      - CUDAExecutionProvider
      #- CPUExecutionProvider
