esp32_bridge:
  ros__parameters:
    serial_port: '/dev/ttyUSB0'
    baud_rate: 115200
    killswitch_address: 66
    killswitch_index: 0
    mission_button_address: 66
    mission_button_index: 1
    mission_button_arm_time_ms: 3000
    leak_sensor_addresses: [66, 69]  # ESP32 board addresses
    leak_sensor_indicies: [0, 4]     # Analog pin indices
    leak_sensor_threshold: 2000.0     # Analog threshold for leak detection
    motor_index_remapping: [1, 4, 7, 3, 5, 0, 2, 6]
