clutch_mega_driver:
  ros__parameters:
    serial_port: '/dev/ttyACM0'
    baud_rate: 115200
    polling_rate: 40.0
    max_throttle: 1650.0
    min_throttle: 1350.0
    motor_index_remapping: [0, 1, 2, 3, 4, 5, 6, 7]
