automated_planner:
  ros__parameters:

    state_timeout_check_period: 0.1

    root:
      gate_distance: 5.0
      turn_marker_one_angle: 90.0
      turn_marker_two_angle: 90.0
      turn_to_octagon_angle: 90.0
      approaching_slalom_distance: 3.0
      approaching_dropper_distance: 2.5
      approaching_octagon_distance: 4.0
      return_home_distance: -10.0
      pass_gate_distance: 3.0
      slalom_turn_one_angle: 45.0
      slalom_move_forward_one_distance: 2.0
      slalom_turn_two_angle: -90.0
      slalom_move_forward_two_distance: 2.0
      mission_altitude: 0.75
      translation_timeout_factor: 3.0
      barrel_roll_angular_velocity: -100.0
      barrel_roll_duration: 7.2
      servo_pwm: 1500.0
      servo_index: 0