accel_control_layer:
  ros__parameters:
    update_frequency: 200.0
    
    # Linear acceleration controllers (acceleration -> force)
    x_linear:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -50.0
      u_max: 50.0
    
    y_linear:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -50.0
      u_max: 50.0
    
    z_linear:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -50.0
      u_max: 50.0
    
    # Angular acceleration controllers (angular acceleration -> torque)
    x_angular:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -20.0
      u_max: 20.0
    
    y_angular:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -20.0
      u_max: 20.0
    
    z_angular:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -20.0
      u_max: 20.0
    
    # Feedforward parameters
    # Mass/inertia scaling factors for feedforward control
    kmass_x: 0.0      # Linear mass coefficient X
    kmass_y: 0.0      # Linear mass coefficient Y
    kmass_z: 0.0     # Linear mass coefficient Z (negative for buoyancy compensation)
    kmass_roll: 0.0   # Roll inertia coefficient
    kmass_pitch: 0.0  # Pitch inertia coefficient
    kmass_yaw: 0.0    # Yaw inertia coefficient
    
    # Drag compensation factors
    kdrag_x: 0.0      # Linear drag coefficient X
    kdrag_y: 0.0      # Linear drag coefficient Y
    kdrag_z: 0.0      # Linear drag coefficient Z
    kdrag_roll: 0.0   # Roll drag coefficient
    kdrag_pitch: 0.0  # Pitch drag coefficient
    kdrag_yaw: 0.0    # Yaw drag coefficient
