accel_control_layer:
    ros__parameters:
        kbuoyancy: -8.35
        kdrag_x: 0.0
        kmass_pitch: 0.4
        kmass_roll: 0.4
        kmass_x: 50.0
        kmass_y: 50.0
        kmass_yaw: 0.4
        kmass_z: 20.0
        x_linear.p_gain: 0.0
