pose_control_layer:
  ros__parameters:
    update_frequency: 200.0
    
    # Linear position controllers
    x_linear:
      p_gain: 0.8
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -5.0
      u_max: 5.0
    
    y_linear:
      p_gain: 0.8
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -5.0
      u_max: 5.0
    
    z_linear:
      p_gain: 1.2
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -3.0
      u_max: 3.0
    
    # Angular position controllers
    x_angular:
      p_gain: 1.5
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -2.0
      u_max: 2.0
    
    y_angular:
      p_gain: 1.5
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -2.0
      u_max: 2.0
    
    z_angular:
      p_gain: 1.0
      i_gain: 0.0
      d_gain: 0.0
      i_min: -1.0
      i_max: 1.0
      u_min: -2.0
      u_max: 2.0