thrust_allocator:
  ros__parameters:
    # Positions are in meters from center of mass, directions are unit vectors 
    # normalized in the thrust allocator so its ok to use more readable values for direction)
    
    #inner motors
    motor_0_position: [0.20, 0.10, -0.05]
    motor_0_direction: [0.0, 0.0, -1.0]
    
    motor_1_position: [0.20, -0.10, -0.05]
    motor_1_direction: [0.0, 0.0, -1.0]
    
    motor_2_position: [-0.20, 0.10, -0.05]
    motor_2_direction: [0.0, 0.0, -1.0]
    
    motor_3_position: [-0.20, -0.10, -0.05]
    motor_3_direction: [0.0, 0.0, -1.0]

    #outer motors
    #front
    #left
    motor_4_position: [0.28, 0.15, -0.05]
    motor_4_direction: [2.0, -1.0, 0.0]
    
    #right
    motor_5_position: [0.28, -0.15, -0.05]
    motor_5_direction: [2.0, 1.0, 0.0]
    
    #back
    #left
    motor_6_position: [-0.22, 0.15, -0.05]
    motor_6_direction: [2.0, 1.0, 0.0]
    
    #right
    motor_7_position: [-0.22, -0.15, -0.05]
    motor_7_direction: [2.0, -1.0, 0.0]
