velocity_control_layer:
  ros__parameters:
    update_frequency: 20.0
    x_angular.p_gain: 0.1
    x_linear.p_gain: 1.0
    y_angular.p_gain: 0.1
    y_linear.p_gain: 1.0
    z_angular.p_gain: 0.1
    z_linear.p_gain: 1.0
    
